async function handleImageScanning(url) {
  const response = await fetch('https://eastus.api.cognitive.microsoft.com/vision/v3.0/analyze?visualFeatures=Objects&language=en', {
    method: 'POST',
    accept: 'application/json',
    headers: {
      'content-type': 'application/json',
      'Ocp-Apim-Subscription-Key': process.env.REACT_APP_IMAGE_PROCESSING_API_KEY,
    },
    body: JSON.stringify({
      "url": url
    })
  })
  const json = await response.json()
  console.log(json.objects)
  return json.objects
}

export async function handleAutoGenerateDescription(url) {
  const response = await fetch('https://eastus.api.cognitive.microsoft.com/vision/v3.0/describe?maxCandidates=1&language=en', {
    method: 'POST',
    accept: 'application/json',
    headers: {
      'content-type': 'application/json',
      'Ocp-Apim-Subscription-Key': process.env.REACT_APP_IMAGE_PROCESSING_API_KEY,
    },
    body: JSON.stringify({
      "url": url
    })
  })
  const json = await response.json()
  console.log(json)
  const captions = json.description.captions.map(caption => caption.text)
  const value = captions[0] + " #" + json.description.tags.join(' #')
  return value
}

export default handleImageScanning